# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  postman-api-test:
    docker:
      - image: circleci/php:7.4-node
    steps:
      - checkout
      - run:
          name: Install newman
          command: sudo npm install -g newman
      - run:
          name: Run postman api tests with newman
          command: newman run "https://api.getpostman.com/collections/19398043-2afa6090-68db-4e09-843b-bc994345fcd5?apikey="$NEWMAN_API
workflows:
  version: 2
  postman-api-test-workflow:
    jobs:
      - postman-api-test
